### ISSUE TITLE
QA Testing

### ISSUE THREAD

**Issue by hughpearse** [hughpearse/DCU-CA683-workspace#14]
Given a release candidate test the implementation:
1. Create a test plan
2. execute the tests
3. Record the results.

Test plan should include missing data and performance evaluation. The architecture document says to "Create a Validation Dataset, Split data into 80%:20% ratio. 80% to train model and 20% to validate dataset".

Review the architecture document (#12) and business requirements (#11) to verify that the requirements are met.

The iris dataset is available here
https://github.com/hughpearse/DCU-CA683-workspace/blob/master/iris.csv

**Comment by MitalKasundra** [comment]
@hughpearse @DeeCorr @DeeCorr 

Getting an error when passing test and training csv to summary.main()
https://drive.google.com/open?id=1XXTQ9rKpuA6OWVf1EUN-DBDcSS0l7SRb

It's trying to calculate the mean of 'class' column.
I think class needs to be coverted to a categorical variable. (like factor in R)

![image](https://user-images.githubusercontent.com/42942512/52206826-5392f200-2873-11e9-8788-538babff419d.png)

**Comment by MitalKasundra** [comment]
evaluator was giving following error.
![image](https://user-images.githubusercontent.com/42942512/52207128-580bda80-2874-11e9-8e58-0f1d92c2f1ce.png)

I fixed it by changing the 
![image](https://user-images.githubusercontent.com/42942512/52207187-812c6b00-2874-11e9-9a68-62533c810e05.png)

**Comment by MitalKasundra** [comment]
Happy with the evaluator file outcome.
If someone fixes error in the summary file, I am happy to move this from QA.

**Comment by MitalKasundra** [comment]
I have fixed the summary code.

Happy to sign off QA.

**Comment by hughpearse** [comment]
@MitalKasundra have you delivered the suggested fixes?

**Comment by MitalKasundra** [comment]
QA Script
https://drive.google.com/open?id=1XXTQ9rKpuA6OWVf1EUN-DBDcSS0l7SRb
