### ISSUE TITLE
Data understanding

### ISSUE THREAD

**Issue by hughpearse** [hughpearse/DCU-CA683-workspace#31]
Steps
1. Open up the instacart data set and browse to see what files and columns might be of interest for a recommender system.
2. Identify any transformations that might need to be made to the data
3. Identify any joins that might need to be made between parts of the data set

Deliverable
Report summarising the structure of the data, the files and columns of interest for a recommender system, and any transformations that might be needed.

**Comment by Araic** [comment]
Liting and I have explored the data and created a Data Understanding document which can be found in the group google drive.
